name: Super Linter

on: [push, pull_request]
    
env:
  folder_name: 'e2e-sdk-prime'

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Super-Linter
      uses: super-linter/super-linter@v5.2.0 
      
