name: Super Linter

on: 
    push:
        branches: [transactionFund]
    pull_request:
        branches: [transactionFund]

env:
  folder_name: 'e2e-sdk-prime'

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Super-Linter
      uses: super-linter/super-linter@v5.2.0 
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: Reports
        OUTPUT_DETAILS: detailed
        IGNORE_GITIGNORED_FILES: true
        VALIDATE_ALL_CODEBASE: true
        
        
        
      
